const guideKey='fight-hub-guided-v1';
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let guide={profile:{goal:'Get fitter',focus:'Full body',location:'Home',experience:'New to training',minutes:'20',equipment:['Chair','Wall'],days:[1,3,5]},plan:null,active:null,index:0,message:''};
try{const s=JSON.parse(localStorage.getItem(guideKey));if(s?.profile&&s?.plan){guide.profile=s.profile;guide.plan=s.plan;}}catch{}
const gbtn=(text,action,id='',cls='full')=>`<button class="${cls}" data-guide="${action}" data-id="${escapeText(id)}">${text}</button>`;
function saveGuide(){try{localStorage.setItem(guideKey,JSON.stringify({profile:guide.profile,plan:guide.plan}));}catch{guide.message='Plan could not be stored. It remains available in this open page.';}}
function diagram(id){return `<button class="movement-image" data-guide="enlarge" data-id="${id}" aria-label="Enlarge ${escapeText(ex(id).name)} movement diagram"><img src="${movementSrc(id)}" alt="AI-generated example positions for ${escapeText(ex(id).name)}. Read the steps below." width="1200" height="800" loading="lazy"><span>Tap to enlarge · AI illustration</span></button>`;}
const beforeGuide=render;
render=function(){beforeGuide();
 if(state.page==='setup'){
 const p=guide.profile;screen.innerHTML=title('Plan my training','Let’s choose<br>your starting point.')+`<p>No exercise knowledge needed. We’ll match available draft sessions to your equipment and focus.</p>${pick('guide-goal','Main goal',['Get fitter','Build strength and muscle','Improve conditioning'],p.goal)}${pick('guide-focus','Today’s focus',['Full body','Upper body','Legs','Shoulders'],p.focus)}${pick('guide-location','Where will you train?',['Home','Gym','Other'],p.location)}${pick('guide-experience','Experience',['New to training','Already training'],p.experience)}${pick('guide-minutes','Time available (minutes)',['10','20','30'],p.minutes)}<fieldset><legend>Equipment available here</legend>${['Chair','Wall','Water bottles','Dumbbells'].map(x=>`<label class="check"><input type="checkbox" data-guide-equipment="${x}" ${p.equipment.includes(x)?'checked':''}>${x}</label>`).join('')}</fieldset><fieldset><legend>Preferred days</legend><div class="day-picker">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=>`<label><input type="checkbox" data-guide-day="${i}" ${p.days.includes(i)?'checked':''}>${day}</label>`).join('')}</div></fieldset><p class="draft-note">This prototype matches equipment and focus only. Goal, experience and time are captured for future reviewed programme matching; they do not yet adjust exercise loads. Shoulder options are mobility-focused, not a complete strength programme.</p>${gbtn('Preview my matched plan','generate','','primary full')}<p role="status">${escapeText(guide.message)}</p>`;
 }
 if(['training','today'].includes(state.page))screen.insertAdjacentHTML('afterbegin',gbtn(guide.plan?'My guided plan':'Plan my training','setup','','primary full'));
 if(state.page==='plan'){
 const plan=guide.plan;screen.innerHTML=title('Your guided week','One clear<br>next step.')+(plan?`<p>${escapeText((guide.plan?.profile||guide.profile).focus)} · ${escapeText((guide.plan?.profile||guide.profile).location)} · ${plan.ids.length} matched movements</p><div class="card feature"><h3>Why these exercises?</h3><p>They match the focus and equipment you selected. This is a draft selection, not a full personalised regime.</p><p class="small">Includes warm-up and cooldown guides. Allow recovery between sets; total strength-session duration is not estimated.</p></div>${plan.days.map(date=>{const h=training.history.find(h=>h.id==='guided-'+date+'-'+plan.created);return `<div class="session"><strong>${escapeText(new Date(date+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}))}</strong><p class="small">${h?(h.complete?'Completed':'Partially logged'):'Planned'}${date===localDate()?' · Today':''}</p>${gbtn(h?'Review / update session':'Open guided session','open',date)}</div>`;}).join('')}<p class="small">Unscheduled days are recovery days. We do not automatically stack missed sessions.</p>${gbtn('Change setup / regenerate week','setup')}`:`<p>Choose your equipment and days to see a matched plan.</p>${gbtn('Plan my training','setup','','primary full')}`);
 }
 if(state.page==='today'&&state.mode!=='fan'&&guide.plan){const today=localDate(),scheduled=guide.plan.days.includes(today),next=guide.plan.days.find(d=>d>=today);screen.innerHTML=title('Today',scheduled?'Your session<br>is ready.':'Room to recover.')+`<div class="card feature"><h3>${scheduled?escapeText((guide.plan?.profile||guide.profile).focus):next?'Next session: '+escapeText(new Date(next+'T12:00:00').toLocaleDateString()):'Your planned week has ended'}</h3><p>${scheduled?'Follow each movement with a diagram and short steps.':'Review your week or update your availability.'}</p>${scheduled?gbtn('Start today’s guided session','open',today,'primary full'):gbtn('View my week','week','','primary full')}</div>${gbtn('Edit training setup','setup')}${act('Browse training library','page','training','full')}`;}
 if(state.page==='guided-session'){
 const a=guide.active;if(!a){screen.innerHTML=gbtn('View my week','week');return;}const id=a.ids[guide.index],m=GuidedModel.movements[id];screen.innerHTML=title(`Guided session / ${guide.index+1} of ${a.ids.length}`,ex(id).name)+diagram(id)+`<p class="draft-note">Illustrative diagram and demo workload; technique and programme review required before release.</p><div class="card"><strong>${m.target}</strong><ol>${m.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p class="small">${m.cue}</p></div><details><summary>Too difficult? See an easier option</summary><p>${m.easy}</p><p class="small">You can skip this exercise; an alternative is not automatically suitable for everyone.</p></details><label class="check"><input id="guided-complete" type="checkbox" ${a.done[id]?'checked':''}> I completed this exercise</label><div class="row">${guide.index?gbtn('Previous','previous','',''):''}${guide.index<a.ids.length-1?gbtn('Next exercise','next','','primary'):''}</div>${gbtn('Swap this movement','swap')}${gbtn('Skip and continue','skip')}${gbtn('Save session / finish','finish','','primary full')}<p role="status">${escapeText(guide.message)}</p>`;
 }
 if(state.page==='exercise'&&GuidedModel.movements[training.selected])screen.insertAdjacentHTML('afterbegin',diagram(training.selected));
 if(guide.active&&state.page!=='guided-session')screen.insertAdjacentHTML('afterbegin',gbtn('Resume guided session','resume'));
 if(['plan','guided-session'].includes(state.page))document.querySelector('[data-go="training"]')?.setAttribute('aria-current','page');
};
document.addEventListener('change',e=>{const map={'guide-goal':'goal','guide-focus':'focus','guide-location':'location','guide-experience':'experience','guide-minutes':'minutes'};if(map[e.target.id])guide.profile[map[e.target.id]]=e.target.value;if(e.target.dataset.guideEquipment){const x=e.target.dataset.guideEquipment;guide.profile.equipment=e.target.checked?[...guide.profile.equipment,x]:guide.profile.equipment.filter(v=>v!==x);}if(e.target.dataset.guideDay!==undefined){const x=Number(e.target.dataset.guideDay);guide.profile.days=e.target.checked?[...guide.profile.days,x]:guide.profile.days.filter(v=>v!==x);}if(e.target.id==='guided-complete')guide.active.done[guide.active.ids[guide.index]]=e.target.checked;});
document.addEventListener('click',e=>{const b=e.target.closest('[data-guide]');if(!b)return;const a=b.dataset.guide,id=b.dataset.id;guide.message='';
 if(a==='setup')return go('setup');if(a==='week')return go('plan');if(a==='resume')return go('guided-session');
 if(a==='generate'){state.mode='train';const ids=GuidedModel.match(guide.profile);if(!ids.length||!guide.profile.days.length){guide.message=!ids.length?'No supported illustrated selection matches this equipment and focus. Change your focus/equipment or browse the library.':'Choose at least one training day.';return render();}guide.plan={created:Date.now(),profile:structuredClone(guide.profile),ids:ids.slice(0,3),days:GuidedModel.dates(localDate(),guide.profile.days)};saveGuide();return go('plan');}
 if(a==='open'){const previous=training.history.find(h=>h.id==='guided-'+id+'-'+guide.plan.created);guide.active={date:id,planCreated:guide.plan.created,profile:structuredClone(guide.plan.profile||guide.profile),ids:previous?previous.entries.map(x=>x.id):[...guide.plan.ids],done:previous?Object.fromEntries(previous.entries.map(x=>[x.id,x.done])):{}};guide.index=0;return go('guided-session');}
 if(a==='previous'){guide.index=Math.max(0,guide.index-1);return render();}if(a==='next'||a==='skip'){if(a==='skip')guide.active.done[guide.active.ids[guide.index]]=false;guide.index=Math.min(guide.active.ids.length-1,guide.index+1);return render();}
 if(a==='swap'){const candidates=GuidedModel.match(guide.active.profile).filter(x=>!guide.active.ids.includes(x));if(!candidates.length){guide.message='No other illustrated movement matches your equipment and focus yet. Use the easier option or skip this movement.';return render();}guide.active.ids[guide.index]=candidates[0];return render();}
 if(a==='finish'){const session=guide.active,key='guided-'+session.date+'-'+session.planCreated;training.history=[{id:key,name:'Guided '+session.profile.focus,date:new Date().toISOString(),entries:session.ids.map(id=>({id,done:!!session.done[id],sets:'',reps:'',minutes:''})),complete:session.ids.every(id=>session.done[id])},...training.history.filter(h=>h.id!==key)].slice(0,100);persistTraining();guide.active=null;return go('progress');}
 if(a==='enlarge'){const dialog=document.createElement('dialog');dialog.className='movement-dialog';dialog.innerHTML=`<h2>${ex(id).name}</h2><img src="${movementSrc(id)}" alt="AI-generated example positions for ${ex(id).name}" width="1200" height="800"><p>AI-generated illustration — technique review pending. Read alongside the movement steps.</p><form method="dialog"><button>Close demonstration</button></form>`;document.body.append(dialog);dialog.addEventListener('close',()=>{dialog.remove();b.focus();});dialog.showModal();}
});
document.querySelector('#reset')?.addEventListener('click',()=>{guide.active=null;render();});
labels.plan='My week';labels.setup='Plan my training';render();
