const hiit={minutes:25,level:'Starter',selection:'Home foundations',run:null,painted:-1};
const hiitButton=(text,action)=>`<button class="full ${action==='start'?'primary':''}" data-hiit="${action}">${text}</button>`;
const beforeHiit=render;
const elapsed=()=>hiit.run.elapsed+(hiit.run.running?(performance.now()-hiit.run.started)/1000:0);
function pauseInterval(){if(hiit.run?.running){hiit.run.elapsed=elapsed();hiit.run.running=false;}}
render=function(){beforeHiit();
 if(['training','builder','today'].includes(state.page))screen.insertAdjacentHTML('afterbegin',hiitButton(hiit.run?'Return to interval session':'HIIT · 25–40 minute sessions','open'));
 if(state.page!=='hiit')return;
 document.querySelector('[data-go="training"]')?.setAttribute('aria-current','page');
 let content=title('Conditioning / HIIT','Build your engine.');
 if(!hiit.run){const plan=ConditioningModel.build({minutes:hiit.minutes,level:hiit.level,circuit:hiit.selection}),setting=ConditioningModel.levels[hiit.level];
 content+=`<p>A complete session: prepare, work, recover and cool down. Start with manageable intervals; the hard setting is for people already comfortable with the movements.</p>${pick('interval-selection','Circuit',Object.keys(ConditioningModel.circuits),hiit.selection)}${pick('interval-level','Difficulty',Object.keys(ConditioningModel.levels),hiit.level)}${pick('interval-minutes','Total session minutes',['25','30','40'],String(hiit.minutes))}<div class="card feature"><span class="eyebrow">${hiit.minutes} minutes total</span><h3>${setting.work}s work / ${setting.rest}s recovery</h3><p>${setting.label}</p><div class="session-breakdown"><span><b>6 min</b>Warm-up</span><span><b>${hiit.minutes-11} min</b>Intervals</span><span><b>5 min</b>Cool-down</span></div><p class="small">${plan.count} work bouts · ${Math.round(plan.workSeconds/60*10)/10} minutes of active work within the interval block. Recovery is included in the total.</p></div><details><summary>Your warm-up and cooldown</summary>${routineMarkup('Warm-up',ConditioningModel.warmup)}${routineMarkup('Cool-down',ConditioningModel.cooldown)}</details><h3>Your exercise rotation</h3><p class="small">Repeat this order until the interval block ends; the final rotation may be partial. Alternate the leading side each bout where relevant.</p>${plan.ids.map((id,i)=>`<div class="session"><span class="eyebrow">${i+1} / ${ex(id).body}</span><h3>${ex(id).name}</h3>${act('How to do it','exercise',id,'full')}</div>`).join('')}<details><summary>How to increase the challenge</summary><p>First repeat the same session with steady technique. Then change just one thing: add 1–2 controlled repetitions within a work interval, select a longer session, or move up one difficulty. There is no need to fill every second with movement.</p><p>Use the recovery intervals. Keep easy or rest days between hard sessions and reduce the session if you have not recovered. No-jumping options can still be demanding.</p></details><p class="draft-note">Original military-inspired circuits, not an official military programme. Start gently; extend the warm-up if needed. Stop if you feel pain or unwell. These draft sessions have not had professional programme review.</p>${hiitButton('Start with the warm-up','start')}`;
 }else{content+=`<div class="card feature"><p id="interval-phase" class="eyebrow"></p><h3 id="interval-exercise"></h3><div id="interval-clock" class="metric" role="timer" aria-label="Time remaining in this phase"></div><p id="interval-round" class="small"></p></div><p id="interval-state" role="status"></p>${hiitButton(hiit.run.running?'Pause session':'Resume session','pause')}${hiitButton('Go to cooldown now','cooldown')}<div id="interval-instruction"></div>${hiitButton('End and reset session','end')}<p class="small">Hiding the page or leaving this screen pauses the timer. Refreshing clears it. Time elapsed is not proof of completing an exercise.</p>`;}
 screen.innerHTML=content;hiit.painted=-1;paintInterval();
};
function routineMarkup(name,phases){return `<h3>${name}</h3>${phases.map(p=>`<p>${ex(p.id).name} · ${p.seconds}s ${act('Instructions','exercise',p.id)}</p>`).join('')}`;}
function paintInterval(){if(state.page!=='hiit'||!hiit.run)return;const p=IntervalModel.position(hiit.run.phases,elapsed());
 if(!document.querySelector('#interval-phase'))return;
 if(p.finished){pauseInterval();document.querySelector('#interval-phase').textContent='Session timer finished';document.querySelector('#interval-exercise').textContent='Recover and reflect.';document.querySelector('#interval-clock').textContent='0:00';document.querySelector('#interval-round').textContent='Mark only the exercises you actually completed.';document.querySelector('#interval-state').textContent='Finished';document.querySelector('[data-hiit="pause"]').disabled=true;document.querySelector('[data-hiit="cooldown"]').disabled=true;if(hiit.painted!==p.index){document.querySelector('#interval-instruction').innerHTML=hiitButton('Create an editable session log','log');hiit.painted=p.index;}return;}
 const phase=hiit.run.phases[p.index];document.querySelector('#interval-phase').textContent=phase.kind;document.querySelector('#interval-exercise').textContent=phase.kind==='Recover'?'Breathe. Reset.':ex(phase.id).name;
 document.querySelector('#interval-clock').textContent=`${Math.floor(p.remaining/60)}:${String(p.remaining%60).padStart(2,'0')}`;
 document.querySelector('#interval-round').textContent=`${phase.station?'Work bout '+phase.station+' of '+hiit.run.count+' · ':''}${hiit.run.minutes} min session · ${Math.ceil(Math.max(0,hiit.run.total-elapsed())/60)} min remaining`;
 document.querySelector('#interval-state').textContent=hiit.run.running?'Running':'Paused';
 if(hiit.painted!==p.index){let html;if(phase.kind==='Recover'){const next=hiit.run.phases[p.index+1];html=`<p>Walk gently or rest in a comfortable position. Take longer recovery if needed.</p><p class="small">Next: ${next?ex(next.id).name:'Finish'}</p>`;}else{const info=ExerciseContent.get(phase.id);html=(typeof movementMedia!=='undefined'?movementMedia(phase.id):'')+`<div class="card"><ol>${info.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p>${info.cue}</p>${phase.kind==='Warm-up'?'<p class="small">Gentle pace and small movements. For squats, use shallow knee bends and pause between repetitions.</p>':''}${phase.kind==='Cool-down'?'<p class="small">Ease the pace down. For each stretch: hold 15–20 seconds, release, and switch sides during this minute; use remaining time to transition. Extend recovery if needed.</p>':''}<details><summary>Easier option</summary><p>${info.easy}</p></details></div>`;}document.querySelector('#interval-instruction').innerHTML=html;hiit.painted=p.index;}
}
document.addEventListener('click',e=>{const a=e.target.closest('[data-hiit]')?.dataset.hiit;if(!a)return;
 if(a==='open')return go('hiit');
 if(a==='start'){const plan=ConditioningModel.build({minutes:hiit.minutes,level:hiit.level,circuit:hiit.selection});hiit.run={...plan,elapsed:0,started:performance.now(),running:true};return render();}
 if(a==='pause'&&hiit.run){if(hiit.run.running)pauseInterval();else{hiit.run.started=performance.now();hiit.run.running=true;}return render();}
 if(a==='cooldown'&&hiit.run){pauseInterval();const start=hiit.run.phases.findIndex(p=>p.kind==='Cool-down');hiit.run.elapsed=hiit.run.phases.slice(0,start).reduce((n,p)=>n+p.seconds,0);hiit.run.started=performance.now();hiit.run.running=true;return render();}
 if(a==='log'&&hiit.run){training.active={id:Date.now()+'-hiit',name:hiit.run.circuit+' · '+hiit.run.level+' · '+hiit.run.minutes+' min timer',paused:false,phase:'main',entries:hiit.run.ids.map(id=>({id,sets:'',reps:'',minutes:'',done:false}))};hiit.run=null;return go('session');}
 if(a==='end'){hiit.run=null;return render();}
});
document.addEventListener('change',e=>{if(e.target.id==='interval-selection')hiit.selection=e.target.value;else if(e.target.id==='interval-level')hiit.level=e.target.value;else if(e.target.id==='interval-minutes')hiit.minutes=Number(e.target.value);else return;render();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseInterval();if(state.page==='hiit')render();}});
setInterval(()=>{if(state.page!=='hiit'){pauseInterval();return;}paintInterval();},200);
document.querySelector('#reset')?.addEventListener('click',()=>{hiit.run=null;render();});
labels.hiit='HIIT';
const resetPreviewButton=document.querySelector('#reset');
const renderBeforeResetPlacement=render;
render=function(){renderBeforeResetPlacement();const premiumSelector=document.querySelector('#steps [data-go="premium"]');if(premiumSelector&&resetPreviewButton)premiumSelector.after(resetPreviewButton);};
render();
