/* Martial-arts preparation drafts. No automatic split-depth progression. */
const MartialMobility={
 'control':{name:'Movement control',tag:'Before training',description:'Practise comfortable ankle, hip and trunk movement before your sport-specific warm-up. This does not teach kicking or replace class preparation.',ids:['ankle','clamshell','side-leg','bird-dog','wall-slide']},
 'front':{name:'Front-split foundations',tag:'Separate flexibility session',description:'Explore hip-flexor and hamstring preparation. This is not a full-split routine or a promise that everyone can reach a split.',ids:['hip-flexor-stretch','hamstring-stretch','half-split','bridge']},
 'middle':{name:'Middle-split foundations',tag:'Separate flexibility session',description:'Build comfortable inner-thigh range and hip control. No forced wide stance, sliding into a split or partner pressure.',ids:['butterfly-stretch','lateral-lunge','clamshell','glute-stretch']}
};
if(typeof module!=='undefined')module.exports=MartialMobility;
if(typeof document!=='undefined'){
const beforeMobility=render;
render=function(){beforeMobility();
 if(['training','today','library'].includes(state.page))screen.insertAdjacentHTML('afterbegin',act('Martial arts mobility & splits preparation','page','mobility','full'));
 if(state.page==='mobility'){
  screen.innerHTML=title('Martial arts / mobility','Range.<br>With control.')+`<p>Flexibility is the range you can reach. Mobility also involves controlling that range. Work at a comfortable level, without chasing the floor.</p><div class="card feature"><span class="badge">FREE FOUNDATIONS</span><h3>Choose your purpose</h3><p>Warm up first. Dynamic preparation and longer held stretches have different roles; use the foundations below to explore them.</p></div>${Object.entries(MartialMobility).map(([key,p])=>`<article class="card"><span class="eyebrow">${p.tag}</span><h3>${p.name}</h3><p>${p.description}</p><details><summary>View ${p.ids.length} movements and instructions</summary>${p.ids.map(id=>`<div class="session"><strong>${ex(id).name}</strong>${act('View instructions and image','exercise',id,'full')}</div>`).join('')}</details><button class="primary full" data-mobility="${key}">Build this session</button></article>`).join('')}<details><summary>How to practise and progress</summary><p>Start with the six-minute gentle warm-up guide. For controlled movements use a small range and the starting examples. For stretches, begin with one gentle 15–20 second hold per side, releasing slowly. Take rest and transition time as needed.</p><p>Choose an easy version you can control. Repeat it comfortably before considering a small change in range. Never force the knees, bounce, hold your breath or have someone push you down. Stop for pain, tingling or joint pinching.</p><p>A full split is optional. Anatomy and training history affect range, and we do not promise a splits deadline. Deeper split work needs qualified instruction.</p></details><div class="card"><h3>A useful progress check</h3><p>Repeat the same movement and setup. Look for comfortable control on each side, steady breathing and an easier return from the position. Do not use pain or distance from the floor as the only measure.</p><p class="small">Session completion can be logged now. Side-by-side mobility assessments and automatic progression are planned, not implemented.</p></div>${act('Compare free and premium','page','premium','full')}<p class="draft-note">Original exercise selections awaiting professional programme review. These are physical-preparation ideas, not martial-arts technique instruction.</p>`;
 }
 if(state.page==='premium'){
 screen.innerHTML=title('Free & Premium','Train today.<br>Build your next chapter.')+`<div class="card feature"><span class="badge">FREE</span><h3>A useful everyday training companion</h3><ul><li>All exercise instructions, illustrations and easier options</li><li>Home sessions, HIIT and martial-arts mobility foundations</li><li>Front- and middle-split preparation selections</li><li>Custom session builder, favourites and local training history</li><li>Basic equipment/focus matching and a dated week</li></ul>${act('Continue with free mobility','page','mobility','primary full')}</div><div class="card"><span class="badge">PREMIUM DEMO</span><h3>Explore extra session selections</h3><p>Try gym push, pull, lower-body, dumbbell and conditioning selections. These are prototype selections, not coached programmes.</p>${act(training.premium?'Return to the free plan':'Try Premium free during early access','toggle-premium','','full')}<p class="small">Premium ${training.premium?'on':'off'} · early access, no payment taken. Access resets when the app is closed.</p></div><div class="card"><span class="badge">PROPOSED PAID PRODUCT · NOT YET BUILT</span><h3>A plan that fits your martial arts</h3><ul><li>Professionally reviewed multi-week strength, conditioning and mobility programmes</li><li>Plan around classes, sparring and recovery days</li><li>Adapt sessions to time, equipment and member feedback</li><li>Compare controlled range and performance over time</li><li>Account-backed history across devices</li></ul><p>These are planned additions, not yet included. Pricing will be set after programme review and member testing.</p></div><p class="small">Basic instructions and easier alternatives stay free. Paid progression should never reward forcing a stretch or ignoring recovery.</p>${act('Browse session collection','page','training','full')}`;
 }
};
document.addEventListener('click',e=>{const key=e.target.closest('[data-mobility]')?.dataset.mobility;if(!key||!MartialMobility[key])return;const p=MartialMobility[key];training.builder=[...p.ids];training.name=p.name;trainingGo('builder');});
labels.mobility='Martial arts mobility';render();
}
