/* Local-only interaction prototype. Never use this client-side tier switch as a real paywall. */
const training = {homeOnly:false,impact:'All',body:'All',equipment:'All',level:'All',query:'',favoritesOnly:false,selected:null,template:null,builder:[],name:'My session',premium:false,favorites:[],history:[],active:null,message:''};
const storeKey='fight-hub-training-preview-v1';
try { const saved=JSON.parse(localStorage.getItem(storeKey)||'null'); if(saved?.version===1){training.favorites=(saved.favorites||[]).filter(id=>FightTraining.exercises.some(e=>e.id===id));training.history=Array.isArray(saved.history)?saved.history.slice(0,100):[];} } catch {training.message='Browser storage is unavailable. This preview will work for this visit.';}
const escapeText=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ex=id=>FightTraining.exercises.find(e=>e.id===id);
function persistTraining(){try{localStorage.setItem(storeKey,JSON.stringify({version:1,favorites:training.favorites,history:training.history}));}catch{training.message='Changes are visible now but could not be saved on this device.';}}
const act=(text,action,id='',cls='')=>`<button class="${cls}" data-training="${action}" data-id="${escapeText(id)}">${text}</button>`;
const draft=()=>`<p class="draft-note">Content preview · exercise selections are editorial drafts, not reviewed training programmes. Choose your own logging targets; nothing is prescribed.</p>`;
const subnav=()=>`<div class="training-tabs">${act('Sessions','page','training')}${act('Exercises','page','library')}${act(`Builder (${training.builder.length})`,'page','builder')}${act('Premium','page','premium')}</div>`;
const pick=(id,label,values,value)=>`<label class="field">${label}<select id="${id}">${values.map(v=>`<option ${v===value?'selected':''}>${escapeText(v)}</option>`).join('')}</select></label>`;
function sessionCard(t){return `<article class="card"><div class="row"><span class="eyebrow">${t.setting} · ${t.focus}</span><span class="badge">${t.premium?'PREMIUM':'FREE'}</span></div><h3>${t.name}</h3><p class="small">${t.description}</p><p class="small">${t.ids.length} exercises · equipment listed inside</p>${act('View session','template',t.id,'full')}</article>`;}
function exerciseResults(){const results=FightTraining.filter({query:training.query,body:training.body,equipment:training.equipment,level:training.level,homeOnly:training.homeOnly,impact:training.impact,favorites:training.favoritesOnly?training.favorites:null});return `<p class="small" role="status">${results.length} exercises found</p>${results.length?results.map(e=>`<article class="exercise-row"><div><span class="eyebrow">${e.body}</span><h3>${e.name}</h3><p class="small">${e.equipment} · ${e.level}</p></div><div class="row">${act('Details','exercise',e.id)}${act(training.favorites.includes(e.id)?icon('heart','icon-filled')+' Saved':icon('heart')+' Save','favorite',e.id)}</div></article>`).join(''):`<div class="card"><h3>No matching exercises</h3><p>Try another muscle group or clear the filters.</p>${act('Clear filters','clear')}</div>`}`;}
const legacyRender=render;
render=function(){
 if(state.page==='workout')state.page='training';
 legacyRender();
 const nav=document.querySelector('#nav');nav.innerHTML=nav.innerHTML.replace('data-go="plan"','data-go="training"');
 const trainingPages=['training','library','exercise','template','builder','session','premium'];
 if(trainingPages.includes(state.page))nav.querySelector('[data-go="training"]').setAttribute('aria-current','page');
 let html='';
 if(state.page==='training')html=title('Train / your library','Choose your<br>next session.')+subnav()+`<div class="card feature"><span class="eyebrow">Made for your routine</span><h3>Start with a session.<br>Make it your own.</h3><p class="small">Browse by focus, explore equipment, or build from the exercise library.</p>${act('Build a custom session','page','builder','primary full')}</div><div class="row"><h3>Session collection</h3><span class="badge">${FightTraining.templates.length} DRAFTS</span></div>${FightTraining.templates.map(sessionCard).join('')}${draft()}`;
 if(state.page==='library')html=title('Exercise library','Find your focus.')+subnav()+`<label class="field">Search exercises<input id="exercise-search" type="search" placeholder="Try squat, row or core" value="${escapeText(training.query)}"></label><div class="filter-grid">${pick('body-filter','Body area',['All',...new Set(FightTraining.exercises.map(e=>e.body))],training.body)}${pick('equipment-filter','Equipment',['All',...new Set(FightTraining.exercises.map(e=>e.equipment))],training.equipment)}</div>${pick('level-filter','Experience',['All','Foundation','Intermediate','Advanced'],training.level)}${pick('impact-filter','Jumping preference',['All','No jumping','Jumping'],training.impact)}<label class="check"><input type="checkbox" id="home-filter" ${training.homeOnly?'checked':''}> Home basics / household equipment</label><label class="check"><input type="checkbox" id="favorites-filter" ${training.favoritesOnly?'checked':''}> Saved exercises only</label><div id="exercise-results">${exerciseResults()}</div>${draft()}`;
 if(state.page==='exercise'){const e=ex(training.selected);if(e)html=title(e.body,e.name)+`<div class="chips"><span class="badge">${e.equipment}</span><span class="badge">${e.level}</span><span class="badge">${e.pattern}</span><span class="badge">${e.impact}</span></div><div class="card feature"><h3>Movement overview</h3><p>${e.description}</p><p class="small">This is a catalogue description. Detailed technique, demonstrations and progression guidance need review before release.</p></div>${e.alternative?`<div class="card"><h3>Prefer no jumping?</h3><p class="small">A different movement option, not a guarantee of suitability.</p>${act(ex(e.alternative).name,'exercise',e.alternative,'full')}</div>`:''}${act(training.builder.includes(e.id)?'Already in session':'Add to my session','add',e.id,'primary full')}${act(training.favorites.includes(e.id)?'Remove from saved':'Save exercise','favorite',e.id,'full')}${act('Back to exercise library','page','library','full')}${draft()}`;}
 if(state.page==='template'){const t=FightTraining.templates.find(x=>x.id===training.template);if(t)html=title(t.premium?'Premium session preview':'Free session preview',t.name)+`<p>${t.description}</p><div class="card"><strong>Equipment to check</strong><p class="small">${[...new Set(t.ids.map(id=>ex(id).equipment))].join(' · ')}</p></div>${t.ids.map(id=>`<div class="session"><strong>${ex(id).name}</strong><span class="small">${ex(id).body} · ${ex(id).equipment}</span>${act('View exercise','exercise',id,'full')}</div>`).join('')}${act(t.premium&&!training.premium?'Explore premium access':'Use this selection','use-template',t.id,'primary full')}${act('Back to sessions','page','training','full')}${draft()}`;}
 if(state.page==='builder')html=title('Session builder','Your session,<br>your selection.')+subnav()+`<label class="field">Session name<input id="session-name" maxlength="60" value="${escapeText(training.name)}"></label><p class="small">${training.builder.length} exercises · no automatic intensity or workload recommendation</p>${training.builder.length?training.builder.map((id,i)=>`<div class="exercise-row"><span class="eyebrow">${i+1} / ${ex(id).body}</span><h3>${ex(id).name}</h3><p class="small">${ex(id).equipment}</p><div class="row">${i?act('Move up','up',id):'<span></span>'}${act('Remove','remove',id)}</div></div>`).join(''):`<div class="card feature"><h3>Choose your first exercise</h3><p>Use body-area and equipment filters to find a starting point.</p></div>`}${act('Add exercises','page','library','full')}${training.builder.length?act('Start logging this session','start','','primary full'):''}<p class="small">Starting creates a new draft log. Any existing unfinished log will be replaced.</p>${draft()}`;
 if(state.page==='session'){const a=training.active;html=title('Workout log',a?escapeText(a.name):'No active session')+(a?`<p class="small">${a.entries.filter(e=>e.done).length} / ${a.entries.length} marked complete · ${a.paused?'Paused':'In progress'}</p>${a.entries.map((entry,i)=>`<div class="card"><span class="eyebrow">${i+1} / ${ex(entry.id).body}</span><h3>${ex(entry.id).name}</h3><fieldset ${a.paused?'disabled':''}><legend class="small">Optional actual work — enter what you did</legend><div class="log-fields"><label>Sets<input type="number" data-log="sets" data-index="${i}" min="0" max="100" value="${escapeText(entry.sets)}"></label><label>Reps<input type="number" data-log="reps" data-index="${i}" min="0" max="1000" value="${escapeText(entry.reps)}"></label><label>Minutes<input type="number" data-log="minutes" data-index="${i}" min="0" max="1440" value="${escapeText(entry.minutes)}"></label></div><label class="check"><input type="checkbox" data-done="${i}" ${entry.done?'checked':''}> Exercise complete</label></fieldset></div>`).join('')}${act(a.paused?'Resume log':'Pause log','pause-log','','full')}${act('Save session log','save-log','','primary full')}<p class="small">Partial sessions count as logged, not completed. Saved history stays in this browser only.</p>`:`${act('Choose exercises','page','builder','primary full')}`);}
 if(state.page==='premium')html=title('Fight Hub Premium','More ways<br>to build your week.')+`<div class="card feature"><span class="badge">${training.premium?'DEMO ACCESS ON':'MEMBERSHIP CONCEPT'}</span><h3>Go beyond the starter collection.</h3><p>Explore the premium session selections in this prototype.</p><ul><li>Gym push, pull and lower-body selections</li><li>Dumbbell and conditioning selections</li><li>Customise the selection before logging</li></ul></div><div class="card"><h3>Planned for the paid product</h3><p class="small">Reviewed multi-week programmes, richer scheduling and deeper progress comparisons. These are not implemented in this preview.</p></div><p>Free includes exercise browsing, saved exercises, the custom builder and your basic history.</p>${act(training.premium?'Return to the free plan':'Try Premium free during early access','toggle-premium','','primary full')}<p class="small">No purchase, account or subscription is created. Price is undecided. Access resets when you refresh.</p>${act('Browse session collection','page','training','full')}`;
 if(state.page==='progress')html=title('Your training history','Every session<br>has a place.')+`<div class="card feature"><div class="metric">${training.history.length}</div><strong>Sessions logged on this device</strong><p class="small">${training.history.filter(h=>h.complete).length} complete · ${training.history.filter(h=>!h.complete).length} partial</p></div>${training.history.length?training.history.map(h=>`<div class="session"><strong>${escapeText(h.name)}</strong><p class="small">${escapeText(new Date(h.date).toLocaleDateString())} · ${h.complete?'Complete':'Partial'} · ${h.entries.length} exercises</p><details><summary>View recorded work</summary>${h.entries.map(e=>`<p class="small">${escapeText(ex(e.id)?.name||e.id)} · ${e.done?'Complete':'Not marked complete'}${e.sets!==''?' · '+escapeText(e.sets)+' sets':''}${e.reps!==''?' · '+escapeText(e.reps)+' reps':''}${e.minutes!==''?' · '+escapeText(e.minutes)+' min':''}</p>`).join('')}</details></div>`).join(''):`<p>Choose a session, record your work and save it here.</p>`}${act('Choose a session','page','training','primary full')}<p class="small">Stored locally, not synced to an account. Avoid entering personal or medical information.</p>${training.history.length?act('Clear local training history','clear-history','','full'):''}`;
 if(html)screen.innerHTML=html;
 if(state.page==='review'&&training.history.length){screen.innerHTML=title('Training review','A record to<br>build on.')+`<div class="card feature"><div class="metric">${training.history.length}</div><strong>Sessions in your local history</strong><p class="small">${training.history.filter(h=>h.complete).length} complete. Partial sessions remain visible too.</p></div><p>Review your recorded work before choosing your next session. This preview does not infer fitness gains or change training loads.</p>${act('View recorded sessions','page','progress','full')}${act('Choose next session','page','training','primary full')}`;}
 if(training.active&&state.page!=='session')screen.insertAdjacentHTML('afterbegin',act('Resume unfinished session','page','session','full'));
 if(state.page==='today'&&state.mode!=='fan'){screen.insertAdjacentHTML('afterbegin',`<div class="training-tabs">${act('Find a session','page','training')}${act('Exercise library','page','library')}${act('Premium','page','premium')}</div>`);const open=screen.querySelector('[data-action="workout"]');if(open){open.textContent='Choose a training session';open.dataset.action='training';} if(training.history.length)screen.insertAdjacentHTML('beforeend',`<div class="card"><h3>Your latest log</h3><p>${escapeText(training.history[0].name)}</p>${act('View training history','page','progress','full')}</div>`);}
 if(state.page==='plan')screen.insertAdjacentHTML('afterbegin',subnav());
 if(training.message)screen.insertAdjacentHTML('afterbegin',`<p class="status" role="status">${escapeText(training.message)}</p>`);
};
function trainingGo(page){training.message='';go(page);}
document.addEventListener('input',e=>{if(e.target.dataset.log&&training.active){training.active.entries[Number(e.target.dataset.index)][e.target.dataset.log]=e.target.validity.valid?e.target.value:'';}if(e.target.id==='exercise-search'){training.query=e.target.value;document.querySelector('#exercise-results').innerHTML=exerciseResults();}if(e.target.id==='session-name')training.name=e.target.value;});
document.addEventListener('change',e=>{const map={'body-filter':'body','equipment-filter':'equipment','level-filter':'level','impact-filter':'impact'};if(map[e.target.id]){training[map[e.target.id]]=e.target.value;render();}if(e.target.id==='home-filter'){training.homeOnly=e.target.checked;render();}if(e.target.id==='favorites-filter'){training.favoritesOnly=e.target.checked;render();}if(e.target.dataset.log){const n=e.target.value;if(!e.target.checkValidity()){e.target.reportValidity();e.target.value='';}training.active.entries[Number(e.target.dataset.index)][e.target.dataset.log]=e.target.value;}if(e.target.dataset.done!==undefined){training.active.entries[Number(e.target.dataset.done)].done=e.target.checked;render();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-training]');if(!b)return;const id=b.dataset.id,a=b.dataset.training;training.message='';
 if(a==='page')return trainingGo(id);
 if(a==='exercise'){training.selected=id;return trainingGo('exercise');}
 if(a==='template'){training.template=id;return trainingGo('template');}
 if(a==='favorite'){training.favorites=training.favorites.includes(id)?training.favorites.filter(x=>x!==id):[...training.favorites,id];persistTraining();return render();}
 if(a==='clear'){Object.assign(training,{homeOnly:false,impact:'All',body:'All',equipment:'All',level:'All',query:'',favoritesOnly:false});return render();}
 if(a==='add'){if(!training.builder.includes(id))training.builder.push(id);training.message='Exercise added to your session.';return render();}
 if(a==='remove'){training.builder=training.builder.filter(x=>x!==id);return render();}
 if(a==='up'){const i=training.builder.indexOf(id);if(i>0)[training.builder[i-1],training.builder[i]]=[training.builder[i],training.builder[i-1]];return render();}
 if(a==='use-template'){const t=FightTraining.templates.find(x=>x.id===id);if(t.premium&&!training.premium)return trainingGo('premium');training.builder=[...t.ids];training.name=t.name;return trainingGo('builder');}
 if(a==='toggle-premium'){training.premium=!training.premium;return render();}
 if(a==='start'){if(!training.builder.length)return;training.active={id:Date.now()+'-'+Math.random().toString(36).slice(2),name:training.name.trim()||'My session',paused:false,entries:training.builder.map(id=>({id,sets:'',reps:'',minutes:'',done:false}))};return trainingGo('session');}
 if(a==='pause-log'){training.active.paused=!training.active.paused;return render();}
 if(a==='save-log'){const session=training.active;if(!session)return;training.history=[{id:session.id,name:session.name,date:new Date().toISOString(),entries:structuredClone(session.entries),complete:session.entries.every(x=>x.done)},...training.history.filter(h=>h.id!==session.id)].slice(0,100);training.active=null;persistTraining();return go('progress');}
 if(a==='clear-history'){training.message='Clear history? This removes only training logs saved by this preview in this browser.';render();screen.insertAdjacentHTML('beforeend',act('Confirm clear history','confirm-clear','','full'));return;}
 if(a==='confirm-clear'){training.history=[];persistTraining();training.message='Local training history cleared.';return render();}
});
document.querySelector('#reset')?.addEventListener('click',()=>{Object.assign(training,{builder:[],active:null,premium:false,message:'Preview reset. Your locally saved favourites and history are retained.'});render();});
delete labels.workout;labels.training='Training';labels.library='Exercises';labels.premium='Premium';
render();
